const sourceLinks=["https://www.instagram.com/stridesoft_/reels/","https://www.instagram.com/erika.ronning/reels/","https://www.instagram.com/shezzasocks/reels/","https://www.instagram.com/reels/DY2-0IKxAWp/","https://www.instagram.com/pawsipus/reels/","https://www.instagram.com/reels/DY54Vr-Tq5Z/","https://www.instagram.com/reels/DYu_-9qufAp/","https://www.instagram.com/reels/DVeZls5jxAe/","https://www.instagram.com/reels/DYJ-qa2K7e_/","https://www.instagram.com/reels/DYYCEyIRvWV/","https://www.instagram.com/reels/DWW5bU8xGcQ/"];
const rows=[["Spin Sneaker","Fashion","Cushioned rotation sneaker concept with visual hook for comfort and daily-wear content."],["Handheld Massage Head Wrap","Beauty","Portable self-care massage product with easy demonstration and wellness angles."],["Satin Sockliner","Fashion","Comfort footwear insert positioned around softness, heel protection, and walking relief."],["CushionFlex Foot Cooling Tube","Beauty","Cooling foot-care product with clear relief story for summer and recovery content."],["Head Massage Therapy Device","Beauty","Relaxation device with strong visual transformation and pain-relief positioning."],["Smart Clay Cleaning Tool","Home","Reusable cleaning product for keyboards, vents, and small dust-prone spaces."],["Digital Sports Watch","Tech","Simple gadget product for fitness routines, steps, and daily performance content."],["Pet Easy Massage Brush","Pet","Pet grooming and massage item with warm owner-pet demo potential."],["Fan Cleaner","Home","Niche cleaning tool with satisfying before-after visuals for dusty home appliances."],["Soft Comfort Insoles","Fashion","Minimal footwear support item for long standing, commuting, and shoe-fit improvement."],["Cooling Gel Eye Pads","Beauty","Reusable gel pads for puffiness and relaxation with strong morning routine angles."],["Padded Socks","Fashion","Comfort sock product with visible cushioning story and everyday wear positioning."],["Magnetic Grip Holder","Tech","Compact phone accessory for hands-free viewing, grip, and quick mounting demos."],["2-in-1 Dog Water Bottle","Pet","Outdoor pet hydration item with travel-friendly benefit and easy demonstration."],["Heat Relief Wrap","Beauty","Body-care wrap for warmth and relief with pain-point driven short-form content."],["Minimal Fold Panel","Home","Simple home utility item suitable for desk, kitchen, and storage problem angles."],["Retractable Pet Leash","Pet","Pet walking accessory with safety, control, and convenience storylines."],["Smart Mini Projector","Tech","Entertainment gadget with strong room setup visuals and giftable positioning."],["Hanging Plant Pot","Home","Home decor product with personalization, indoor plant, and small-space angles."],["Wireless Smart Switch Set","Tech","Home automation accessory for renter-friendly smart room upgrades."]];
const products=rows.map((item,index)=>{const score=94-Math.floor(index*1.7);const trend=96-((index*7)%31);const profit=88-((index*5)%34);const competition=28+((index*6)%46);return{id:`product-${index+1}`,name:item[0],category:item[1],description:item[2],image:`assets/products-square/product-${String(index+1).padStart(2,"0")}.webp`,source:sourceLinks[index%sourceLinks.length],score,trend,profit,competition,tags:[item[1],trend>82?"High Demand":"Steady Demand",profit>72?"Good Margin":"Test First"]}});
const list=document.querySelector("#productList"),searchInput=document.querySelector("#searchInput"),sortSelect=document.querySelector("#sortSelect"),visibleCount=document.querySelector("#visibleCount"),totalCount=document.querySelector("#totalCount");let activeCategory="all";
function visibleProducts(){const q=searchInput.value.trim().toLowerCase();return[...products].filter(p=>activeCategory==="all"||p.category===activeCategory).filter(p=>!q||[p.name,p.category,p.description,...p.tags].join(" ").toLowerCase().includes(q)).sort((a,b)=>b[sortSelect.value]-a[sortSelect.value])}
function metricRow(label,value,color=""){return`<div class="metric"><span>${label}</span><span class="bar ${color}"><span style="width:${value}%"></span></span><strong>${value}</strong></div>`}
function renderProducts(){const items=visibleProducts();visibleCount.textContent=`${items.length} products`;totalCount.textContent=products.length;if(!items.length){list.innerHTML='<div class="empty">검색 조건에 맞는 제품이 없습니다.</div>';return}list.innerHTML=items.map((p,i)=>`<article class="product-card"><div class="thumb"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="rank">#${String(i+1).padStart(2,"0")}</span></div><div class="card-body"><div class="card-top"><h3 class="card-title">${p.name}</h3><span class="score">${p.score}</span></div><p class="desc">${p.description}</p><div class="pill-row">${p.tags.map(t=>`<span class="pill">${t}</span>`).join("")}</div><div class="metrics">${metricRow("Trend",p.trend)}${metricRow("Profit",p.profit,"yellow")}${metricRow("Comp.",p.competition,"orange")}</div><div class="actions"><a class="primary" href="${p.source}" target="_blank" rel="noreferrer">Source</a><button type="button">Details</button></div></div></article>`).join("")}
document.querySelectorAll("[data-category]").forEach(btn=>btn.addEventListener("click",()=>{document.querySelectorAll("[data-category]").forEach(i=>i.classList.remove("active"));btn.classList.add("active");activeCategory=btn.dataset.category;renderProducts()}));searchInput.addEventListener("input",renderProducts);sortSelect.addEventListener("change",renderProducts);renderProducts();
const communityForm=document.querySelector("#communityForm"),communityFeed=document.querySelector("#communityFeed"),communityStatus=document.querySelector("#communityStatus");
function esc(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;")}
function relativeTime(d){const diff=Math.max(0,Date.now()-new Date(d).getTime()),m=Math.floor(diff/60000);if(m<1)return"방금 전";if(m<60)return`${m}분 전`;const h=Math.floor(m/60);if(h<24)return`${h}시간 전`;return`${Math.floor(h/24)}일 전`}
function renderCommunity(posts){if(!communityFeed)return;communityFeed.innerHTML=posts.map(p=>`<article class="post"><div class="avatar">${esc((p.name||"M").slice(0,1).toUpperCase())}</div><div><strong>${esc(p.title)}</strong><p>${esc(p.message)}</p><span>${esc(p.name)} · ${relativeTime(p.createdAt)}</span></div></article>`).join("")}
async function loadCommunity(){if(!communityFeed)return;try{const r=await fetch("/api/community");if(!r.ok)throw new Error("no api");renderCommunity(await r.json());communityStatus.textContent="Live"}catch{communityStatus.textContent="Demo";renderCommunity([{name:"K",title:"이번 주 반려동물 제품 소스 공유",message:"릴스 반응 좋은 강아지 물병 제품을 찾았습니다. 경쟁도는 낮고 시연 영상 만들기 쉬워요.",createdAt:new Date().toISOString()},{name:"H",title:"첫 판매 인증",message:"미니 프로젝터 제품으로 상세페이지 테스트 후 첫 주문 들어왔습니다.",createdAt:new Date(Date.now()-3600000).toISOString()}])}}
if(communityForm){communityForm.addEventListener("submit",async e=>{e.preventDefault();const payload={name:document.querySelector("#communityName").value,title:document.querySelector("#communityTitle").value,message:document.querySelector("#communityMessage").value};try{const r=await fetch("/api/community",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});if(r.ok){communityForm.reset();await loadCommunity();return}}catch{}communityStatus.textContent="Demo only"});loadCommunity();setInterval(loadCommunity,8000)}
